lat: 45.  # latitude (deg)
lon: 0.  # longitude (deg)
alt: 0.  # altitude (m)
azm: 0.  # azimuth (deg)

month: 3  # month number (1=Jan, 2=Feb, ...)
day: 21  # day of the month
hour: 12  # hour of the day (in [0, 23] range)

Ta: 15.  # ambient temperature (C)
Pa: 1.0E+05  # ambient pressure (Pa)
rh: 0.8  # relative humidity (none, in [0, 1])
pr: 0.  # rain precipitation rate (m.s**-1)
ws: 0.  # wind speed (m.s**-1)
wa: 90.  # wind angle (deg, regarding north)
al: 0.8  # albedo (1)
tb: 0.1 # coefficient for air pollution from 0 (clean) to 1 (polluted)

I: 100.  # transit intensity (A)

m: 1.5  # mass per unit length (kg.m**-1)
d: 1.9E-02  # core diameter (m)
D: 3.0E-02  # external (global) diameter (m)
a: 2.84E-04  # core section (m**2)
A: 7.07E-04  # external (global) section (m**2)
R: 4.0E-02  # roughness (1)
l: 1.0  # radial thermal conductivity (W.m**-1.K**-1)
c: 500.  # specific heat capacity (J.kg**-1.K**-1)

alpha: 0.5  # solar absorption (1)
epsilon: 0.5  # emissivity (1)
RDC20: 2.5E-05  # electric resistance per unit length (DC) at 20°C (Ohm.m**-1)
km: 1.006  # coefficient for magnetic effects (1)
ki: 0.016  # coefficient for magnetic effects (A**-1)
kl: 3.8E-03  # linear resistance augmentation with temperature (K**-1)
kq: 8.0E-07  # quadratic resistance augmentation with temperature (K**-2)
RDCHigh: 3.05E-05  # electric resistance per unit length (DC) at THigh (Ohm.m**-1)
RDCLow: 2.66E-05  # electric resistance per unit length (DC) at TLow (Ohm.m**-1)
THigh: 60.  # temperature for RDCHigh measurement (°C)
TLow: 20.  # temperature for RDCLow measurement (°C)
